[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
shared = { workspace = true }
aes-gcm = { workspace = true }
x25519-dalek = { workspace = true }
windows = { workspace = true}
lazy_static = "1.4.0"
xcap = "0.0.10"
image = { workspace = true }