[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
bincode = { workspace = true }
shared = { workspace = true }
aes-gcm = { workspace = true }
x25519-dalek = { workspace = true }
windows = { workspace = true}
lazy_static = "1.4.0"
xcap = "0.0.10"
image = { workspace = true }
dirs = "5.0.1"
jzon = "0.12.5"
base64 = "0.22.1"
rusqlite = {version = "0.32.1", features = ["bundled"]}
cc = "1.1.15"
aes = "0.8.4"
cbc = "0.1.2"