[workspace]
resolver = "2"

members = [
    "client",
    "server",
    "shared"
]

[workspace.dependencies]
tokio = {version = "1.37.0", features=["net", "rt", "io-std", "macros", "io-util", "sync", "time", "rt-multi-thread", "fs"]}
bincode = "1.3.3"
serde = {version = "1.0.200", features = ["derive"]}
shared = {path="./shared"}
aes-gcm = "0.10.3"
x25519-dalek = "2.0.1"
windows = {version = "0.56.0", features=["Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_TextServices",
                                         "Media_Capture", "Media_MediaProperties", "Graphics_Imaging", "Storage_Pickers", "Storage_Streams",
                                         "Win32_Graphics_Gdi", "Graphics_Capture"]}
image = "0.25.1"