[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
shared = { workspace = true}
aes-gcm = { workspace = true }
x25519-dalek = { workspace = true }
tokio-util = "0.7.11"
image = { workspace = true }
chrono = "0.4.38"
rusqlite = {workspace = true}
lazy_static = { workspace = true }
rsa = { workspace = true }
